name: CI

on:
  push:
    branches: [master, ci]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: sudo apt-get install -y libdrm-dev libxkbcommon-dev libudev-dev
      - uses: BSFishy/meson-build@v1.0.3
        with:
          meson-version: 0.63.3
          action: build
          setup-options: -Dwlroots:examples=false -Dwlroots:renderers=gles2 -Dwlroots:xcb-errors=disabled -Dflutter_wlroots:examples=true

#meson build --reconfigure -Dwlroots:examples=false -Dwlroots:renderers=gles2 -Dwlroots:xcb-errors=disabled -Dflutter_wlroots:examples=true
