name: CI

on:
  push:
    branches: [master, ci]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: sudo apt-get install -y libdrm-dev libxkbcommon-dev libudev-dev libwayland-dev libegl-dev libgles-dev libinput-dev libseat-dev seatd
      - uses: BSFishy/meson-build@v1.0.3
        with:
          meson-version: 0.63.3
          action: install
          setup-options: -Dwlroots:examples=false -Dwlroots:renderers=gles2 -Dwlroots:xcb-errors=disabled -Dflutter_wlroots:examples=true --destdir install
      - uses: actions/upload-artifact@v3
        with:
          name: full_build
          path: build
      - uses: actions/upload-artifact@v3
        with:
          name: install
          path: install

#meson build --reconfigure -Dwlroots:examples=false -Dwlroots:renderers=gles2 -Dwlroots:xcb-errors=disabled -Dflutter_wlroots:examples=true
